---
- name: Query existing drive groups
  ansible.builtin.command: sudo graidctl ls dg --format=json
  become: true
  register: existing_dg_output
  changed_when: false

- name: Parse existing drive groups
  ansible.builtin.set_fact:
    existing_dg_list: "{{ (existing_dg_output.stdout | from_json).Result | map(attribute='DgId') | list }}"

- name: Check if new physical drives are available
  ansible.builtin.fail:
    msg: "No new physical drives found for creating drive groups."
  when: >
    (configure_create_by_numa and not pd_list_by_numa) or
    (configure_create_by_socket | int > 0 and not pd_list_by_socket) or
    (not configure_create_by_numa and configure_create_by_socket | int == 0 and not pd_list_all)

- name: Debug - Show detailed condition evaluation
  ansible.builtin.debug:
    msg:
      - "configure_create_by_numa: {{ configure_create_by_numa }}"
      - "configure_create_by_numa (as bool): {{ configure_create_by_numa | bool }}"
      - "configure_create_by_socket: {{ configure_create_by_socket }}"
      - "configure_create_by_socket (as int): {{ configure_create_by_socket | default('-1') | int }}"
      - "Condition 1 result: {{ configure_create_by_numa | bool }}"
      - "Condition 2 result: {{ configure_create_by_socket | default('-1') | int < 0 }}"
      - "Overall condition result: {{ (configure_create_by_numa | bool) and (configure_create_by_socket | default('-1') | int < 0) }}"

- name: Debug - Check condition
  ansible.builtin.debug:
    msg: "Condition met for creating drive groups by NUMA"
  when:
    - configure_create_by_numa | bool
    - configure_create_by_socket | default('-1') | int < 0

- name: Create drive groups by NUMA
  become: true
  ansible.builtin.command: >
    graidctl create dg {{ configure_raid_type }} {{ item.value | join(',') }}
    {% if configure_dg_foreground_init %} -z{% endif %}
  loop: "{{ pd_list_by_numa | dict2items }}"
  when:
    - configure_create_by_numa | bool
    - configure_create_by_socket == '' or configure_create_by_socket | int < 0
  register: create_dg_numa_results
  changed_when: false

- name: Create drive groups by Socket
  become: true
  ansible.builtin.command: >
    graidctl create dg {{ configure_raid_type }} {{ item.value | join(',') }}
    {% if configure_dg_foreground_init %} -z{% endif %}
  loop: "{{ pd_list_by_socket | dict2items }}"
  when:
    - configure_create_by_socket | int > 0
    - not configure_create_by_numa | bool
  register: create_dg_socket_results
  changed_when: false

- name: Create single drive group
  become: true
  ansible.builtin.command: >
    graidctl create dg {{ configure_raid_type }} {{ pd_list_all | join(',') }}
    {% if configure_dg_foreground_init %} -z{% endif %}
  when: not configure_create_by_numa and configure_create_by_socket | int == 0
  register: create_dg_single_result
  changed_when: false

- name: Query new drive groups
  become: true
  ansible.builtin.command: graidctl ls dg --format=json
  register: new_dg_output
  changed_when: false

- name: Parse new drive groups and find newly added DgIds
  ansible.builtin.set_fact:
    new_dg_list: "{{ (new_dg_output.stdout | from_json).Result | map(attribute='DgId') | list }}"
    newly_added_dg_list: "{{ (new_dg_output.stdout | from_json).Result | map(attribute='DgId') | list | difference(existing_dg_list) }}"

# - name: Debug - Check condition
#   ansible.builtin.debug:
#     var:
#       - { { new_dg_list } }
#       - { { newly_added_dg_list } }

- name: Verify new drive groups were created
  ansible.builtin.fail:
    msg: "Failed to create any new drive groups."
  when: newly_added_dg_list | length == 0
  changed_when: false

- name: Wait for drive groups to initialize
  become: true
  ansible.builtin.command: graidctl ls dg --format=json
  register: dg_status_output
  until: (dg_status_output.stdout | from_json).Result | selectattr('DgId', 'in', newly_added_dg_list) | map(attribute='State') | list | unique == ['OPTIMAL']
  retries: 1000000
  delay: 60
  when: configure_dg_foreground_init | bool
  changed_when: false

- name: Debug output of newly created drive groups
  ansible.builtin.debug:
    msg: "Newly created drive groups: {{ newly_added_dg_list }}"
