---
# Validate boolean parameters
- name: Validate boolean parameters
  ansible.builtin.assert:
    that:
      - configure_pd_hotspare | bool is boolean
      - configure_delete_raid | bool is boolean
      - configure_create_by_numa | bool is boolean
      - configure_edit_dg | bool is boolean
      - configure_cc_mode | bool is boolean
      - configure_dg_foreground_init | bool is boolean
    fail_msg: >
      "The following parameters must be boolean:
      configure_pd_hotspare: {{ configure_pd_hotspare }},
      configure_delete_raid: {{ configure_delete_raid }},
      configure_create_by_numa: {{ configure_create_by_numa }},
      configure_edit_dg: {{ configure_edit_dg }},
      configure_cc_mode: {{ configure_cc_mode }},
      configure_dg_foreground_init: {{ configure_dg_foreground_init }}"

# Validate parameters with predefined options
- name: Validate list option parameters
  ansible.builtin.assert:
    that:
      - configure_pd_sorting in valid_pd_attributes
      - configure_pd_create_attribute in valid_pd_attributes
      - configure_raid_type in valid_raid_type
      - configure_dg_pd_vwc in valid_dg_pd_vwc
      - configure_dg_spdk_bdev in valid_dg_spdk_bdev
      - configure_dg_journal in valid_dg_journal
      - configure_cc_schedule in valid_cc_schedule
      - configure_cc_policy in valid_cc_policy
    fail_msg: >
      Invalid options specified:
      PD sorting attribute: '{{ configure_pd_sorting }}',
      PD create attribute: '{{ configure_pd_create_attribute }}',
      RAID type: '{{ configure_raid_type }}',
      DG PD VWC: '{{ configure_dg_pd_vwc }}',
      DG SPDK BDEV: '{{ configure_dg_spdk_bdev }}',
      DG journal: '{{ configure_dg_journal }}',
      CC schedule: '{{ configure_cc_schedule }}',
      CC policy: '{{ configure_cc_policy }}'.
      Please check the valid options for each parameter.

# Validate DG speed attributes
- name: Validate DG speed attributes
  ansible.builtin.assert:
    that:
      - configure_dg_rebuild_speed in valid_dg_speed_attributes
      - configure_dg_init_speed in valid_dg_speed_attributes
      - configure_dg_cc_speed in valid_dg_speed_attributes
      - configure_dg_resync_speed in valid_dg_speed_attributes
    fail_msg: "Invalid speed setting. Valid options are: {{ valid_dg_speed_attributes | join(', ') }}"

# Validate VD count
- name: Validate configure_vd_counts
  ansible.builtin.assert:
    that:
      - configure_vd_counts | int > 0
    fail_msg: "configure_vd_counts must be a positive integer"

# Validate VD size
- name: Validate configure_vd_size
  ansible.builtin.assert:
    that:
      - configure_vd_size | regex_search('^[0-9]+[KMGT]B$') or configure_vd_size == ''
    fail_msg: >
      Invalid VD size format. Use format like '500MB', '1GB', '2TB',
      or leave empty for full capacity

# Validate socket configuration
- name: Validate configure_create_by_socket
  ansible.builtin.assert:
    that:
      - configure_create_by_socket | regex_search('^[0-9,]*$') or configure_create_by_socket == ""
    fail_msg: "configure_create_by_socket must be a comma-separated list of numbers or empty"
