---
- name: SupremeRAID Installation Playbook
  hosts: supremraid_servers
  become: true
  gather_facts: true

  vars_files:
    - vars/supremeraid_vars.yaml
    - vars/download_urls.yaml

  pre_tasks:
    - name: Gather OS Distribution Facts
      ansible.builtin.setup:
      register: dist
      tags: always

    - name: Check internet connectivity
      ansible.builtin.command: ping -c 1 8.8.8.8
      register: ping_result
      ignore_errors: true
      changed_when: false
      tags: always

    - name: Set install mode to online if internet is available
      ansible.builtin.set_fact:
        install_mode: "online"
      when: ping_result.rc == 0
      tags: always

    - name: Display install mode
      ansible.builtin.debug:
        msg: "Install mode is {{ install_mode }}"
      tags: always

  tasks:
    - name: Run prepare tasks
      import_role:
        name: prepare
      tags: [prepare]
    
    - name: Run install tasks
      import_role:
        name: install
      tags: [install]
    
    - name: Run configure tasks
      import_role:
        name: configure
      tags: [configure]

  post_tasks:
    - name: Fail if unsupported OS
      fail:
        msg: "Unsupported operating system: {{ ansible_distribution }}"
      when: ansible_os_family not in ["RedHat", "Debian", "Windows"]
      tags: unsupported
