---
- name: SupremeRAID Installation Playbook
  hosts: supremraid_servers
  gather_facts: true

  # vars_files:
  #   - vars/supremeraid_vars.yaml
  #   - vars/download_urls.yaml

  pre_tasks:
    - name: Gather OS Distribution Facts
      ansible.builtin.setup:
      register: dist
      tags:
        - always

    - name: Test reachability to 8.8.8.8
      ansible.builtin.command: ping -c 2 8.8.8.8
      ignore_errors: true
      register: ping_result
      changed_when: false
      tags:
        - always

    - name: Debug variables
      ansible.builtin.debug:
        msg:
          - "graid_path: {{ graid_path | default('undefined') }}"
          - "linux: {{ linux | default('undefined') }}"
          - "linux.pre_installer_url: {{ linux.pre_installer_url | default('undefined') }}"
      tags:
        - always
    # - name: Test reachability to 8.8.8.8
    #   ansible.netcommon.net_ping:
    #     dest: 8.8.8.8
    #     count: 2
    #   tags:
    #     - always

    # - name: Check internet connectivity
    #  ansible.builtin.command: ping -c 1 8.8.8.8
    #  register: ping_result
    #  ignore_errors: true
    # changed_when: false
    #  tags: always

    - name: Set install mode to online if internet is available
      ansible.builtin.set_fact:
        install_mode: "online"
      when: ping_result.rc == 0
      tags:
        - always

    - name: Display install mode
      ansible.builtin.debug:
        msg: "Install mode is {{ install_mode }}"
      tags:
        - always

    # Disk space check in a block with rescue
    - name: Check disk space
      tags:
        - always
      block:
        - name: Calculate available space on / partition
          ansible.builtin.set_fact:
            free_space_gb: >-
              {{
                (ansible_facts.mounts
                | selectattr('mount', 'equalto', '/')
                | map(attribute='size_available')
                | first
                | float / 1024 / 1024 / 1024)
                | round(2)
              }}

        - name: Check available space on / partition and fail if insufficient
          ansible.builtin.fail:
            msg: >-
              Insufficient space on / partition. Current free space: {{ free_space_gb }}GB.
              Required: greater than {{ min_disk_space_gb }}GB
          when: free_space_gb | float < min_disk_space_gb | float

        - name: Display success message if space is sufficient
          ansible.builtin.debug:
            msg: >-
              Sufficient space on / partition. Current free space: {{ free_space_gb }}GB.
              Meets requirement (greater than {{ min_disk_space_gb }}GB)
      rescue:
        - name: Fail the play if disk space check failed
          ansible.builtin.fail:
            msg: "Playbook execution stopped due to insufficient disk space."


  tasks:
    - name: Run prepare tasks
      ansible.builtin.import_role:
        name: prepare
      tags:
        - prepare

    - name: Run Driver_setup_install tasks
      ansible.builtin.import_role:
        name: install
      tags:
        - install

    - name: Run configure tasks
      ansible.builtin.import_role:
        name: configure
      tags:
        - configure

  post_tasks:
    - name: Fail if unsupported OS
      ansible.builtin.fail:
        msg: "Unsupported operating system: {{ ansible_distribution }}"
      when: ansible_os_family not in ["RedHat", "Debian", "SLES", "Windows"]
      tags: unsupported
