---
# handlers file for configure
- name: Restart graid-mgr service
  ansible.builtin.systemd:
    name: graid-mgr.service
    state: restarted
  become: true

- name: Reload firewall
  ansible.builtin.command: firewall-cmd --reload
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  register: firewall_reload_result
  changed_when: "'success' in firewall_reload_result.stdout"

- name: Restart graid server
  become: true
  ansible.builtin.service:
    name: graid.service
    state: restarted
  when: vmc_changed | bool
