---
# tasks file for copy_files
- name: Ensure local download directory exists
  delegate_to: localhost
  ansible.builtin.file:
    path: "./local_downloads"
    state: directory

- name: Download pre-installer to control node
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ pre_installer_url }}"
    dest: "./local_downloads/{{ pre_installer_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family != "Windows"

- name: Download installers to control node
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "./local_downloads/{{ item | basename }}"
    mode: "0755"
  loop: "{{ installer_urls }}"
  when:
    - ansible_os_family != "Windows"

- name: Copy pre-installer to remote host
  ansible.builtin.copy:
    src: "./local_downloads/{{ pre_installer_url | basename }}"
    dest: "~/graid_package/{{ pre_installer_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family != "Windows"

- name: Copy installers to remote host
  ansible.builtin.copy:
    src: "./local_downloads/{{ item | basename }}"
    dest: "~/graid_package/{{ item | basename }}"
    mode: "0755"
  loop: "{{ installer_urls }}"
  when:
    - ansible_os_family != "Windows"

- name: Download nv dirver to control node
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ nv_url }}"
    dest: "./local_downloads/{{ nv_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family == "Windows"

- name: Download Installation script to control node
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ installation_script_url }}"
    dest: "./local_downloads/{{ installation_script_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family == "Windows"

- name: Download installers to control node
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "./local_downloads/{{ item | basename }}"
    mode: "0755"
  loop: "{{ installer_win_urls }}"
  when:
    - ansible_os_family == "Windows"

- name: Copy nv dirver to remote host
  ansible.windows.win_copy:
    src: "./local_downloads/{{ nv_url | basename }}"
    dest: "C:\\Temp\\{{ nv_url | basename }}"
  when:
    - ansible_os_family == "Windows"

- name: Copy Installation script to remote host
  ansible.windows.win_copy:
    src: "./local_downloads/{{ installation_script_url | basename }}"
    dest: "C:\\Temp\\{{ installation_script_url | basename }}"
  when:
    - ansible_os_family == "Windows"

- name: Copy installers to remote host
  ansible.windows.win_copy:
    src: "./local_downloads/{{ item | basename }}"
    dest: "C:\\Temp\\{{ item | basename }}"
  loop: "{{ installer_win_urls }}"
  when:
    - ansible_os_family == "Windows"
