---
# tasks file for prepare
- name: Identify system
  ansible.builtin.include_tasks: identify_system.yml
  args:
    apply:
      tags:
        - identify
  tags:
    - identify

- name: Query serial
  ansible.builtin.include_tasks: query_serial.yml
  args:
    apply:
      tags:
        - query
  tags:
    - query

- name: Check NVIDIA Driver
  ansible.builtin.include_tasks: check_nv_driver.yml
  args:
    apply:
      tags:
        - nvidia
  tags:
    - nvidia
