# tasks file for upgrade_check
- name: Update apt cache and upgrade packages (Debian/Ubuntu)
  become: true
  when: ansible_os_family == "Debian"
  tags:
    - upgrade
  block:
    - name: Update apt
      ansible.builtin.shell: apt-get update -y ; apt-get upgrade -y

    - name: Check if a reboot is needed after upgrade
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the Debian or Ubuntu server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

- name: Update yum cache and upgrade packages (Red Hat/CentOS)
  become: true
  when: ansible_os_family == "RedHat"
  tags:
    - upgrade
  block:
    - name: Update yum cache
      ansible.builtin.command: yum update -y
      failed_when: false

    - name: Install yum-utils
      ansible.builtin.command: yum install yum-utils -y
      failed_when: false

    - name: Check if a reboot is needed after upgrade
      ansible.builtin.command: needs-restarting -r
      register: needs_restarting_result
      failed_when: false

    - name: Reboot the Red Hat or CentOS server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: "'Reboot is required' in needs_restarting_result.stdout"
