# group_vars/configure.yml
configure_pd_hotspare: false
configure_raid_type: "raid5"
valid_raid_type:
  - raid0
  - raid1
  - raid5
  - raid6
  - raid10
configure_vd_size: ""
configure_vd_counts: 1

configure_delete_raid: false

configure_create_by_numa: false
configure_create_by_socket: ""
configure_pd_sorting: "Address"
configure_pd_create_attribute: "NQN"
valid_pd_attributes:
  - Numa
  - DevPath
  - Address
  - NQN

configure_dg_foreground_init: false
configure_dg_pd_vwc: "off"
valid_dg_pd_vwc:
  - "on"
  - "off"

configure_dg_spdk_bdev: "disable"
valid_dg_spdk_bdev:
  - enable
  - disable

configure_dg_journal: "degrade_only"
valid_dg_journal:
  - always_off
  - degrade_only
  - always_on

configure_dg_rebuild_speed: "high"
configure_dg_init_speed: "high"
configure_dg_cc_speed: "high"
configure_dg_resync_speed: "high"
valid_dg_speed_attributes:
  - low
  - normal
  - high
  - extreme
