# General variables
general:
  license_table_path: "{{ playbook_dir }}/roles/configure/files/license_mapping.csv"
  device_model_name: "QEMU NVMe Ctrl"
  graid_mgr_ports: 50060
  copy_from_local: true
  timeout: 300
  min_disk_space_gb: 2 # Minimum required free space in GB, DO NOT change this value.

# Setup configuration
setup:
  metadata_file: "https://download.graidtech.com/misc/tools/tmp/metadata_graid_urls.json"
  graid_path: "{{ ansible_env.HOME }}/graid_package/"
  install_mode: "offline"
  remote_os: "linux"
  miniconda_version: "latest"
  conda_env_name: "graid_ansible_env"
  python_version: "3.11"
  inventory_file: "ansible_supremeraid/inventory/hosts"
  log_dir: "logs"
  ping_count: 3
  ping_timeout: 5
  max_retries: 3
  retry_delay: 5

# Main configuration
configure_pd:
  create_by_numa: false
  create_by_socket: ""
  create_attribute: "NQN"
  sorting: "Address"

configure_raid:
  type: "raid5"
  vd_size: ""
  vd_counts: 1
  delete: false
  dg_foreground_init: false

configure_mount_point:
  set_mount_point: false
  set_fstab: true
  filesystem: "xfs"
  mount_point: "/mnt/graid"
  options:
    basic: "noatime,nodiratime"
    systemd: "x-systemd.requires=graid.service"
    extra: "nofail"

configure_consistency_check:
  mode: false
  schedule: "off"
  policy: "stop_on_error"

configure_disk_group:
  edit_dg: false
  pd_hotspare: false
  pd_vwc: "off"
  spdk_bdev: "disable"
  journal: "degrade_only"
  rebuild_speed: "high"
  init_speed: "high"
  cc_speed: "high"
  resync_speed: "high"

configure_import_md:
  enabled: false
  devices:
    - /dev/sda
    - /dev/sdb

configure_nvme_of:
  initiator: false
  target: false
  connect: false
  export: false
  ip_addr: ""
  ports:
    - "4420"
  addr_family: ipv4
  transport_type: rdma
  target_interface:
    - "eth0"

# Valid values for various configuration options
configure_valid:
  pd_attributes:
    - Numa
    - DevPath
    - Address
    - NQN
  raid_type:
    - raid0
    - raid1
    - raid5
    - raid6
    - raid10
  cc_schedule:
    - "off"
    - "continuously"
    - "hourly"
    - "daily"
    - "weekly"
    - "monthly"
  cc_policy:
    - stop_on_error
    - auto_fix
  pd_vwc:
    - "on"
    - "off"
  spdk_bdev:
    - enable
    - disable
  journal:
    - always_off
    - degrade_only
    - always_on
  speed_attributes:
    - low
    - normal
    - high
    - extreme
  nvme_of_addr_family:
    - ipv4
    - ipv6
  nvme_of_transport_type:
    - rdma
    - tcp
    - fc
