---
- name: Include identify_system role
  include_tasks: ../prepare/tasks/identify_system.yml

- name: Set default values and query devices
  import_tasks: prepare_devices.yml

- name: Create physical drives
  import_tasks: create_physical_drives.yml

- name: Create drive groups
  import_tasks: create_drive_groups.yml

- name: Create virtual drives
  import_tasks: create_virtual_drives.yml
