---
- name: Include identify_system role
  ansible.builtin.include_tasks: ../prepare/tasks/identify_system.yml

- name: Normal create process
  when: not configure_nvme_of.connect | default(false) | bool
  block:
    - name: Set default values and query devices
      ansible.builtin.include_tasks: create/prepare_devices.yml

    - name: Validate configs
      ansible.builtin.include_tasks: create/validate_configs.yml

    - name: Create physical drives
      ansible.builtin.include_tasks: create/create_physical_drives.yml

    - name: Create drive groups
      ansible.builtin.include_tasks: create/create_drive_groups.yml

    - name: Create virtual drives
      ansible.builtin.include_tasks: create/create_virtual_drives.yml

- name: Create NVME-oF target device process
  when: configure_nvme_of.connect | default(false) | bool
  block:
    - name: Run NVMe-oF initiator tasks
      ansible.builtin.include_tasks: nvme_of/initiator.yml
