---
# tasks file for configure
- name: Activate service
  ansible.builtin.import_tasks: activate_service.yml
  tags: [activate]

- name: Configure RAID
  ansible.builtin.import_tasks: create_raid.yml
  tags: [raid]
  when: not configure_delete_raid

- name: Uncompose RAID
  ansible.builtin.import_tasks: delete_raid.yml
  tags: [delete]
  when: configure_delete_raid