---
# tasks file for configure
- name: Activate service
  ansible.builtin.include_tasks: common/activate_service.yml
  args:
    apply:
      tags:
        - activate
  tags:
    - activate

- name: Setup RAID
  ansible.builtin.include_tasks: create_raid.yml
  args:
    apply:
      tags:
        - raid
  tags:
    - raid
  when: not configure_raid.delete | default(false)  | bool

- name: Uncompose RAID
  ansible.builtin.include_tasks: delete_raid.yml
  args:
    apply:
      tags:
        - delete
  tags:
    - delete
  when: configure_raid.delete | default(false)  | bool


- name: Edit drive_group
  ansible.builtin.include_tasks: common/edit_dg.yml
  args:
    apply:
      tags:
        - edit_dg
  tags:
    - edit_dg
  when: configure_raid.edit | default(false)  | bool

- name: Setup NVMe-of initiator
  ansible.builtin.include_tasks: nvme_of/initiator.yml
  args:
    apply:
      tags:
        - nvmeof
        - initiator
  tags:
    - initiator
    - nvmeof
  when:
    - configure_nvme_of.initiator | default(false)  | bool
    - not  configure_nvme_of.target | default(false)  | bool

- name: Setup NVMe-of target
  ansible.builtin.include_tasks: nvme_of/target.yml
  args:
    apply:
      tags:
        - nvmeof
        - target
  tags:
    - target
    - nvmeof
  when:
    - not configure_nvme_of.initiator | default(false)  | bool
    - configure_nvme_of.target | default(false)  | bool
