---
# tasks file for copy_files
- name: Ensure local download directory exists
  delegate_to: localhost
  become: true
  ansible.builtin.file:
    path: "{{ graid_path }}"
    state: directory
    mode: "0755"

- name: Download pre-installer to control node
  delegate_to: localhost
  become: true
  ansible.builtin.get_url:
    url: "{{ linux.pre_installer_url }}"
    dest: "{{ graid_path }}{{ linux.pre_installer_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family != "Windows"

- name: Download installers to control node
  delegate_to: localhost
  become: true
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ graid_path }}{{ item | basename }}"
    mode: "0755"
  loop: "{{ linux.installer_urls }}"
  when:
    - ansible_os_family != "Windows"

- name: Copy pre-installer to remote host
  become: true
  ansible.builtin.copy:
    src: "{{ graid_path }}{{ linux.pre_installer_url | basename }}"
    dest: "{{ graid_path }}{{ linux.pre_installer_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family != "Windows"

- name: Copy installers to remote host
  become: true
  ansible.builtin.copy:
    src: "{{ graid_path }}{{ item | basename }}"
    dest: "{{ graid_path }}{{ item | basename }}"
    mode: "0755"
  loop: "{{ linux.installer_urls }}"
  when:
    - ansible_os_family != "Windows"

- name: Download nv dirver to control node
  become: true
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ windows.nv_url }}"
    dest: "{{ graid_path }}{{ windows.nv_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family == "Windows"

- name: Download Installation script to control node
  become: true
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ windows.installation_script_url }}"
    dest: "{{ graid_path }}{{ windows.installation_script_url | basename }}"
    mode: "0755"
  when:
    - ansible_os_family == "Windows"

- name: Download installers to control node
  become: true
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ graid_path }}{{ item | basename }}"
    mode: "0755"
  loop: "{{ windows.installer_win_urls }}"
  when:
    - ansible_os_family == "Windows"

- name: Copy nv dirver to remote host
  become: true
  ansible.windows.win_copy:
    src: "{{ graid_path }}{{ windows.nv_url | basename }}"
    dest: "C:\\Temp\\{{ windows.nv_url | basename }}"
  when:
    - ansible_os_family == "Windows"

- name: Copy Installation script to remote host
  become: true
  ansible.windows.win_copy:
    src: "{{ graid_path }}{{ windows.installation_script_url | basename }}"
    dest: "C:\\Temp\\{{ windows.installation_script_url | basename }}"
  when:
    - ansible_os_family == "Windows"

- name: Copy installers to remote host
  become: true
  ansible.windows.win_copy:
    src: "{{ graid_path }}{{ item | basename }}"
    dest: "C:\\Temp\\{{ item | basename }}"
  loop: "{{ windows.installer_win_urls }}"
  when:
    - ansible_os_family == "Windows"
