---
# tasks file for run_installer

- name: Check if the conf file exists
  ansible.builtin.stat:
    path: "/etc/graid.ansible.conf"
  register: driver_conf_stats
  become: true

- name: Set the conf type once update
  ansible.builtin.lineinfile:
    path: /etc/graid.ansible.conf
    line: "1"
    create: true
    mode: "0644"
  become: true
  tags:
    - update

- name: Include query_serial role
  ansible.builtin.include_tasks: ../prepare/tasks/query_serial.yml

- name: GPU model shown
  ansible.builtin.debug:
    msg: "GPU: {{ query_gpu_name + ' (' + installer_suffix + ')' }}"

- name: Set installer filename
  ansible.builtin.set_fact:
    installer_filename: "graid-sr-installer-*-{{ installer_suffix }}-*.run"

- name: Debug installer filename
  ansible.builtin.debug:
    msg: "Installer filename: {{ installer_filename }}"

- name: Find the correct installer file in /graid_package
  ansible.builtin.find:
    paths: "{{ setup.graid_path }}"
    patterns: "{{ installer_filename }}"
  register: found_files
  become: true

- name: Debug found_files filename
  ansible.builtin.debug:
    msg: "Installer filename: {{ found_files }}"

- name: Fail if installer file not found
  ansible.builtin.fail:
    msg: "Installer file not found: {{ installer_filename }}"
  when: found_files.matched == 0

- name: Determine execute or not
  when: installation_type | int != 0 or  driver_conf_stats.stat.exists is not defined or not driver_conf_stats.stat.exists
  block:
    - name: Check if the old_installation-installer log file exists
      ansible.builtin.stat:
        path: "/var/log/graid-installer/installer.log "
      register: installer_log_stats

    - name: Remove and backup the old_installation log
      ansible.builtin.copy:
        src: /var/log/graid-installer/installer.log
        dest: /var/log/graid-installer/installer.log.bak
        remote_src: true
        force: true
        mode: "0644"
      become: true
      when: installer_log_stats.stat.exists

    - name: Set installer path
      ansible.builtin.set_fact:
        installer_path: "{{ found_files.files[0].path }}"

    - name: Run the installer
      ansible.builtin.command: "bash {{ installer_path }} --accept-license"
      async: "{{ general.timeout | int * 5 }}"
      poll: 0
      register: install_result
      changed_when: false

    - name: Wait for installer log file to be created
      ansible.builtin.wait_for:
        path: /var/log/graid-installer/installer.log
        state: present
        timeout: "{{ general.timeout  }}"

    - name: Monitor installer log file
      ansible.builtin.wait_for:
        path: /var/log/graid-installer/installer.log
        search_regex: "\\[INFO\\] Asking reboot\\?"
        timeout: "{{ general.timeout | int / 10 }}" # 180 * 10 seconds = 1800 seconds = 30 minutes
      register: log_content
      become: true
      retries: 180
      delay: 10
      ignore_unreachable: true
      until: log_content is succeeded

    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors

    - name: Wait for the server to finish rebooting
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: "{{ general.timeout  }}"

    - name: Check network connectivity after installer
      ansible.builtin.ping:
      register: ping_result_after_installer
      ignore_errors: true

    - name: Wait for SSH to come back
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 30
        timeout: "{{ general.timeout | int * 5  }}"
        state: started
      when: ping_result_after_installer is failed
      ignore_unreachable: true

    - name: Set conf
      ansible.builtin.copy:
        content: "0"
        dest: /etc/graid.ansible.conf
        mode: "0644"
      become: true
      register: conf_result
      changed_when: conf_result.changed
