---
# tasks file for install
# - name: Download packages
#   ansible.builtin.include_tasks: download_packages.yml
#   args:
#     apply:
#       tags:
#         - downloads
#   tags:
#     - downloads

- name: Copy files
  ansible.builtin.include_tasks: copy_files.yml
  args:
    apply:
      tags:
        - copy
  tags:
    - copy
  # when: install_mode == 'offline'

- name: Setup environment (Online)
  ansible.builtin.include_tasks: online_setup.yml
  args:
    apply:
      tags:
        - setup
  tags:
    - setup
  when: install_mode == 'online'

- name: Setup environment (Offline)
  ansible.builtin.include_tasks: offline_setup.yml
  args:
    apply:
      tags:
        - setup
  tags:
    - setup
  when: install_mode == 'offline'

- name: Run installer
  ansible.builtin.include_tasks: driver_installer.yml
  args:
    apply:
      tags:
        - driver
        - update
  tags:
    - driver
    - update