---
# tasks file for install
- name: Download packages
  ansible.builtin.import_tasks: download_packages.yml
  tags:
    - downloads

- name: Copy files
  ansible.builtin.import_tasks: copy_files.yml
  tags:
    - copy
  when: install_mode == 'offline'

- name: Setup environment (Online)
  ansible.builtin.import_tasks: online_setup.yml
  tags:
    - setup
  when: install_mode == 'online'

- name: Setup environment (Offline)
  ansible.builtin.import_tasks: offline_setup.yml
  tags:
    - setup
  when: install_mode == 'offline'

- name: Run installer
  import_tasks: driver_installer.yml
  tags:
    - driver
    - update

