---
# tasks file for online_install

- name: Run SupremeRAID pre-installer in online mode
  ansible.builtin.command: "bash {{ graid_path }}{{ linux.pre_installer_url | basename }} --yes"
  async: 1800
  poll: 0
  become: true
  register: preinstaller_job

- name: Monitor pre-installer log file
  ansible.builtin.command: |
    tail -n 10 -f /var/log/graid-preinstaller/preinstaller.log | grep -m 1 "\\[INFO\\] Selected 'Yes' for reboot system\\."
  register: log_content
  until: log_content.rc == 0
  become: true
  retries: 180
  delay: 10
  changed_when: false
  failed_when: false
  ignore_unreachable: true

- name: Clear host errors
  ansible.builtin.meta: clear_host_errors

- name: Wait for the server to finish rebooting
  ansible.builtin.wait_for_connection:
    delay: 30
    timeout: 300

- name: Check network connectivity after pre-installer
  ansible.builtin.ping:
  register: ping_result_after_preinstaller
  ignore_errors: true

- name: Wait for SSH to come back
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 30
    timeout: 1200
    state: started
  when: ping_result_after_preinstaller is failed
  ignore_unreachable: true

- name: Pause to allow service to start or stop
  ansible.builtin.pause:
    seconds: 60
  when: ping_result_after_preinstaller is failed
